<?xml version="1.0" encoding="utf-8"?><Database Name="StudentDB" Class="BorrowDataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\StudentDB.mdf;Integrated Security=True" SettingsObjectName="Library_Manage_System.Properties.Settings" SettingsPropertyName="StudentDBConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BorroeTb" Member="BorroeTbs">
    <Type Name="BorroeTb">
      <Column Name="Student_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Student_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Book_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gat_Date" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Return_Date" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>