<?xml version="1.0" encoding="utf-8"?><Database Name="StudentDB" Class="LibrarianDataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\StudentDB.mdf;Integrated Security=True" SettingsObjectName="Library_Manage_System.Properties.Settings" SettingsPropertyName="StudentDBConnectionString5" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LibrarianTb" Member="LibrarianTbs">
    <Type Name="LibrarianTb">
      <Column Name="Librarian_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Librarian_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Adress" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone_No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>